version: '3'
services:
  app:
    container_name: snippetbox
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - mynet
    command: ["/usr/local/bin/snippetbox/wait-for-mysql.sh", "db", "/usr/local/bin/snippetbox/init.sh"]

  db:
    container_name: database
    build: ./docker/mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: snippet_root_pass
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    restart: always
    networks:
      - mynet

networks:
  mynet:
    driver: "bridge"